#' Generate Stream Features Dataset
#'
#' This function runs samples to create a dataset output for use in discharge volume calculations.
#' @param nsample Number of samples to generate.
#' @return Writes a CSV file containing the stream features dataset.
#' @export
#' @examples
#' stream_features(nsample=100)
stream_features <- function(nsample=100) {
  library(dplyr)
  library(here)
  library(tidyverse)
  
  depth_samp <- runif(nsample, min=1, max=20)
  velocity_samp <- runif(nsample, min=.1, max=10)
  stream_features = data.frame(depth=depth_samp, velocity=velocity_samp, width=2)
  stream_features <- stream_features |>
    mutate(velocity_type = cut(velocity, breaks = c(.1,3,5,10),
                               labels = c("low","medium","high"),
                               include.lowest=TRUE)) |>
    mutate(measure = row_number())
  
  write_csv(stream_features, here("stream_features.csv"))
  
  return(stream_features)
}

# Now, call the function to generate the stream_features dataframe
stream_features <- stream_features(nsample=100) # Set the number of samples you want

# You can now use stream_features in your environment

#' Stream Features Dataset
#'
#' This dataset is generated by the `stream_data` function and contains measurements related to the flow and characteristics of streams. It is intended for hydrology and environmental science research.
#'
#' @format A data frame with 100 rows and 5 variables:
#' \describe{
#'   \item{depth}{Numeric. Depth of the stream in meters.}
#'   \item{velocity}{Numeric. Flow velocity of the stream in meters per second.}
#'   \item{width}{Integer. Width of the stream in meters.}
#'   \item{velocity_type}{Factor. Qualitative assessment of flow velocity (low, medium, high).}
#'   \item{measure}{Integer. Identifier for the measurement event.}
#' }
#' @source Generated by `stream_data()` function.


